# -*- coding: utf-8 -*-
"""Matplotlib

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V0w3lG0CBKgMbW77pY_cE1UHKMi85dJZ

# **Matplotlib Intro**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

year=[2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020]
temp=[72,65,66,34,84,87,85,77,72,68,67]
plt.plot(year,temp) #ordering matplotlib to plot a line graph
plt.xlabel('Year') #Naming the x axis
plt.ylabel('Temperature') #naming the y axis
#defining the title of the graph to be made and its alignment and fontsize
plt.title('Global Warming',{'fontsize':20,'horizontalalignment':'center'})
plt.show()

"""# *Generate graph of random electricity consumption*"""

month=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
cust1=[]
cust2=[]
cust3=[]
for i in range(0,12):
    rdno=np.random.randint(30,150)
    rdno2=np.random.randint(20,110)
    rdno3=np.random.randint(30,100)
    cust1.append(rdno)
    cust2.append(rdno2)
    cust3.append(rdno3)
plt.plot(month,cust1,color='Red',label='Customer 1',marker="o")
plt.plot(month,cust2,color='Blue',label='Customer 2', marker="o")
#plt.title('Electricity consumption for the year 2021 \n',{'fontsize':20, 'horizontalalignment':'center'})
plt.xlabel('\n Months')
plt.ylabel('Electricity consumption in KWh \n')
plt.grid()
plt.legend(loc="lower left")

"""**Sub Charts**"""

plt.subplot(1,2,1)
plt.plot(month,cust1,color='Red',label='Customer 1',marker="o")
plt.title('Electricity consumption for the year 2021 \n',{'fontsize':20, 'horizontalalignment':'center'})
plt.ylabel('Electricity consumption in KWh \n')

plt.subplot(1,2,2)
plt.plot(month,cust2,color='Blue',label='Customer 2', marker="o")
plt.xlabel('\n Months')
plt.ylabel('Electricity consumption in KWh \n')

"""**Scatter Chart**"""

plt.scatter(month,cust1,color='red',label='Customer 1')
plt.scatter(month,cust2,color='blue',label='Customer 2')
plt.title('Scatter plot')
plt.xlabel('\n Months')
plt.ylabel('Electricity consumption in KWh \n')
plt.grid()

"""**Histogram Chart**"""

plt.hist(cust1, bins=80,color='red')
plt.title('Electricity consumption for the year 2021 \n',{'fontsize':20, 'horizontalalignment':'center'})
plt.xlabel('\n Months')
plt.ylabel('Electricity consumption in KWh \n')

"""**Bar chart**"""

plt.bar(month,cust1,color='red',width=0.4)
plt.bar(month,cust2,color='blue',width=0.4)
plt.title('Electricity consumption for the year 2021 \n',{'fontsize':20, 'horizontalalignment':'center'})
plt.xlabel('\n Months')
plt.ylabel('Electricity consumption in KWh \n')

"""**Bar chart with different bars showing different capacities yet exclusive**"""

bar_width=0.2
month_b=np.arange(12)
print(month_b)
plt.bar(month_b,cust1,bar_width,color='r',label='Customer 1')
plt.bar(month_b+bar_width,cust2,bar_width,color='b',label='Customer 2')
plt.bar(month_b+(bar_width*2),cust3,bar_width,color='g',label='Customer 3')
plt.legend()
plt.xticks(month_b +(bar_width)/12,('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'))

"""**Understanding Boxplot**"""



