# -*- coding: utf-8 -*-
"""Numpy & Pandas Prac

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iNpzDFJJrU4YlVmYMOglt7MgFAZi7TGl

## **NUMPY TUTORIAL**
"""

import numpy as np

arr1=np.array([[1,2,3],[2,4,5],[2,3,6]])
arr2=np.array([[2,3,4],[8,5,4],[5,6,8]])

"""**Sum & Difference of arrays in numpy**"""

sum_array=arr1+arr2
print(sum_array)

print(arr1-arr2)

print(np.subtract(arr1,arr2))

"""**Adding all the elements row wise and column wise in an array**"""

print(np.sum(arr1))

"""**Dot Multiplication**"""

mnp=arr1@arr2
print(mnp)

print(np.dot(arr1,arr2))

"""**Element by element multiplication**"""

print(arr1*arr2)

maul=np.multiply(arr1,arr2)
print(maul)

"""**Division in Numpy**"""

div=np.divide(arr1,2)
print(div)

print(np.floor_divide(arr1,2))

"""**Math Class in NUMPY**"""

print(np.math.sqrt(36))

"""### **Random Array Creation in Numpy**

**Generating Standard Normal arrays**
"""

random_arr=np.random.standard_normal((3,4)) #generated array with 3 rows 4 column
print(random_arr)

"""**Generating Uniform Distributed array**"""

random_arr2=np.random.uniform(1,12,(3,4)) #generated array with 3 rows & 4 columns and number ranging from 1 to 12 
print(random_arr2)

"""**Generating Array of different datatypes**"""

eg1=np.random.randint(1,10,(4,4)) #Generated an array with integer number
print(eg1)

ze=np.zeros((3,4))
print(ze)

ek=np.ones((3,4))
print(ek)

print(np.random.rand())

"""**Creating Logical table in Numpy**"""

Random_Ar=np.random.randint(1,250,(2,5))
filter_ar=np.logical_and(Random_Ar>30,Random_Ar<50)

print(filter_ar)

frandom_ar=np.logical_or(Random_Ar>30,Random_Ar<50)
print(frandom_ar)

"""**Statistics in Numpy**"""

dataset=np.array([1,3,4,5,7,9])
mean_dat=np.mean(dataset)
print(mean_dat)

median_dat=np.median(dataset)
print(median_dat)

var_dat=np.var(dataset)
print(var_dat)

sd_dat=np.std(dataset)
sd_dat1=np.math.sqrt(var_dat)
print(sd_dat)
print(sd_dat1)

var_arr1=np.var(arr1,axis=1) #calculates variance for each row of array and shows its variance
var_arr1col=np.var(arr1,axis=0) # calculates the variance for each column values)
print(var_arr1)
print(var_arr1col)

"""## **Pandas Library**"""

import pandas as pd

"""**Creating a small dataframe**"""

age=pd.Series([10,20,30,40],index=['age1','age2','age3','age4'])

print(age)

"""Constraints for displaying specific data from dataframe"""

age.age3

Filtered_age=age[age>20]
print(Filtered_age)

"""Calling values %Indexes"""

print(age.values)
print(age.index)

age.index=['a1','a2','a3','a4']
print(age.index)

"""**DataFrames**"""

df=np.array([[20,10,8],[25,8,10],[27,5,3],[30,9,7]])
dat_set=pd.DataFrame(df)
print(dat_set)

"""**Setting row and column names**"""

dat_set1=pd.DataFrame(df,index=['s1','s2','s3','s4'],columns=['Sub1','Sub2','Sub3'])
print(dat_set1)

"""Adding dataset to existing dataframe"""

dat_set1['Sub4']=[9,6,7,10]
print(dat_set1)

"""**To display the data from a specific row**"""

dat_set1.loc['s2']

dat_set1.loc['s2']['Sub1']

dat_set1.iloc[2,3]

dat_set1.iloc[:,3]

dat_set1.iloc[:,0]

dat_set1.iloc[:,1:4]

"""**Deletion for displaying of Specific Column**"""

dat_set1.drop('Sub4',axis=1) #mention axis for specifying deletion from rows and columns

dat_set1.replace(10,12) #replaces all 10s in dataframes to 12

dat_set1.replace({12:10,9:30})

dat_set1.head(3)

dat_set1.tail(3)

dat_set1.sort_index(axis=0,ascending=True)

"""**Working with CSV file**"""

dat_csv=pd.read_csv('/content/Data_Set.csv')

print(dat_csv)

